FROM node:alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000

FROM minddocdev/node-alpine
WORKDIR /home
COPY --from=builder /app /home
CMD ["npm", "run", "start:dev"]